### ISSUE TITLE
Additional Skip Cutscene Vignettes

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/wotw-rando-client#216]
Currently some cutscenes are still unskippable or have odd side effects such as dying at the start of Kwolok chase.
There are further disadvantages with the current system, such as the Mora fight having no Abandon Challenge options.

Probably the smoothest solution that could be worth exploring is to add Skip Cutscene options to these cutscenes, like some other ones already have.

**Comment by toadettexmushina** [comment]
In a similar vein - it would be nice to skip the reach escape cutscene.

Additionally, adding an Abandon Challenge option to the hide and seek section in wastes. Currently, to quit it you must QTM and then load a backup save. Attempting to load a backup save without QTM just loads you back into the chase.

**Comment by timoschwarzer** [comment]
The skippable cutscenes header only skips cutscenes that cannot be skipped otherwise afaik. It is possible to skip the reach cutscene. (It also has the nice risk factor of not giving you a checkpoint if you skip it)

**Comment by timoschwarzer** [comment]
Done / obsolete
