### ISSUE TITLE
Inaccurate uberState restoration on death

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/wotw-rando-client#238]
The stats uberStates preserving through death have an inaccuracy: They are reset to the moment where Ori died, but there still is an animation time between the moment of death and respawning, changes to e.g. the timer uberState during this animation get overwritten.
This can be relatively short (spike death) or multiple seconds worth of time (silent woods mud).

**Comment by SiriusAshling** [comment]
This is one of many issues that would be solved by moving stats out of the uberState system, which is not useful for this purpose.
Not sure it's worth trying to hackfix minor corrections together, doubt that the system will ever work correctly as long as it's based on uberStates.

**Comment by MunWolf** [comment]
What we probably want is to move it all to the launcher and just query it for the stats in the credits.
(We can do this by generating a guid on new game and using that as an identifier to the launcher, then even if you play the same seed 2 times they won't share stats)

**Comment by timoschwarzer** [comment]
Done
