### ISSUE TITLE
Inconsistent mute syntax

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/wotw-rando-client#244]
the effect of `|mute` currently does different things depending on context:
In a message pickup, it hides all the *other* items on a multipickup's display message
In a non-message pickup, it hides *this* item from the multipickup's display message

Both are useful tools, however it is confusing that they are behind the same keyword since they have opposite effects.
Further there is a flag to remove the message box sound (`quiet`), which can also be confusing since mute sounds like it could have that effect as well.

From a language design perspective, the variant used most of the time (mute on a message to hide everything else) also has some pitfalls (e.g. hiding other messages not marked with `mute`) making it easy to write incorrect code.

It may be better to present the currently less used variant (hide this item) as the primary tool, for instance as a `|hide` flag that always has the same effect: Hiding that line from the multipickup's display message.

This should be a much saner and more reliable tool than the current one. Not to lose functionality there could also be a `|hideothers` flag (intentionally long to write) preserving the functionality currently present for message pickups, although it should probably be discouraged to use if there isn't a good reason to prefer it over the `|hide` flag.

**Comment by MunWolf** [comment]
If we want to tackle this, do we keep the original mute and quiet keywords for legacy support or bite the bullet and remove them?

**Comment by SiriusAshling** [comment]
Both variants are used in existing seeds, so I would suggest to add the new flags without removing the old `mute`. And `quiet` seems good as a name, not sure that needs any changes.

**Comment by MunWolf** [comment]
Is there a point to having hide available for message pickups?
Since the only point of message pickups is to display the message.

**Comment by SiriusAshling** [comment]
Probably not, at least so far messages have no side effects
