### ISSUE TITLE
Opening the Eyestone door from the other side

### ISSUE THREAD

**Issue by Foopyo** [ori-community/wotw-rando-client#249]
The eyestone door (the statue between Marsh and Hollow) can only be opened from the Marsh side of the door.

It would be better if that door could also be opened from the Hollow side of the door because of fully random spawn could spawn you there.

**Comment by toadettexmushina** [comment]
Reminding myself to remove this door from open mode if this happens.

**Comment by MunWolf** [comment]
This one is a bit tricky and will require some investigation, this is pretty much because technically the 'door' collision box is only in front of the head. So we would probably have to special case this particular door and do a second bounds check inside of the head.

**Comment by toadettexmushina** [comment]
The biggest issue with this is apart from fully random spawn, there's no reason to need this unless the purple bow door is also openable from the back. And I'm guessing straight up putting a second bow switch near the Hollow TP is probably more change/programming than anyone wants to do.

**Comment by sparkle-preference** [comment]
could just do a header where tp+bow = door open tho? like the moldwood
autoopen on glide header

**Comment by toadettexmushina** [comment]
That... honestly, I think I would prefer that to the current thing where mouldwood and the bow door are just open. I'll see if I can figure out how that works and maybe update open mode.

**Comment by timoschwarzer** [comment]
But then wolf can't pull a wolf anymore on that door 🥲

**Comment by toadettexmushina** [comment]
why would that change?
you still need keystones to open it?

**Comment by timoschwarzer** [comment]
> why would that change? you still need keystones to open it?

Forgot to make a reply, it was directed at Eikos suggestion of auto-opening it

**Comment by toadettexmushina** [comment]
> > why would that change? you still need keystones to open it?
> 
> Forgot to make a reply, it was directed at Eikos suggestion of auto-opening it

I think Eiko's suggestion was directed at me regarding the purple bow door, not the eyestone door - which is why I thought it was a good idea.

**Comment by timoschwarzer** [comment]
Done in 3.0
