### ISSUE TITLE
Unsorted Twillen shop

### ISSUE THREAD

**Issue by Foopyo** [ori-community/wotw-rando-client#270]
Items in Twillen shop are sorted in an ascending order according to the SL amount. This is already kinda disorienting when opening the shop again after buying some things but it'll also make it hard to spot the Black Market Gorlek Ore slot.

Add a way to fix Twillen's shop items order

**Comment by SiriusAshling** [comment]
Don't think the sorting is really necessary anymore, icons already do a lot for orientation.

**Comment by MunWolf** [comment]
> Don't think the sorting is really necessary anymore, icons already do a lot for orientation.

Pretty sure this sorting is vanilla behaviour, don't think we are doing this intentionally (at least I can't see the code where we would be)

**Comment by SiriusAshling** [comment]
ahhh yes that makes sense.
Well that makes it a bit harder to customize this to our needs

**Comment by timoschwarzer** [comment]
Done in 3.0
