### ISSUE TITLE
KS door above Baur

### ISSUE THREAD

**Issue by Coder23848** [ori-community/wotw-rando-client#294]
According to the map, there's a keystone door above Baur's cave. Teleporting to it reveals that it is in the space below the Avalanche Escape, but it's out of bounds and the door does not exist.
![image](https://user-images.githubusercontent.com/103940315/166266886-3cde4850-7c02-4c47-941d-2b54b3878ba1.png)

**Comment by MunWolf** [comment]
Once I rewrite map_icons.cpp Ill have a look at this.

**Comment by timoschwarzer** [comment]
Fixed in 3.0 and moved to the correct place (Kwolok Eyestone door)
