### ISSUE TITLE
Moving uberStates

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/wotw-rando-client#298]
It might be considerable to move some poorly placed uberStates with the breaking changes of 2.0

The [header converter](https://github.com/ori-rando/header-converter) could automatically migrate them to the new identifiers.

**Comment by SiriusAshling** [comment]
The price states for Glades Lupo are currently in the "npcsStateGroup" used by the vanilla game, which makes them hard to find.

This is inconsistent with other price states, which are in the uberState group of their respective NPCs.

It would make significantly more sense for the Lupo Glades prices to be in the "lupo" group, which already contains the prices for all other Lupos

**Comment by SiriusAshling** [comment]
The "game_state" group contains a "Goal Modes Complete" state which does not fit with the theme of other uberStates in that group and would likely fit better under "rando_state"

**Comment by timoschwarzer** [comment]
We should maybe do our yearly clean up for 3.0 again?
