### ISSUE TITLE
A way to bring back Ku

### ISSUE THREAD

**Issue by Foopyo** [ori-community/wotw-rando-client#311]
It's currently impossible to set the Ku quest uberstate (`14019|34504`) to the value needed in order to have Ku in Woods because of the ShouldRevert function from [UberStateController.cs](https://github.com/ori-rando/wotw-client/blob/074f66ec313b6ec94503e0e1bbb57abc18327356/projects/RandoMainDLL/UberStateController.cs#L481). This function reverts every changes done to the Ku quest uberstate, if it's set to a smaller value than 4, which is the state at which Ku dies.

Thanks to a header language bug, it was previously possible to hack Ku in by using this command `14019|34504=4|8|14019|34504|int|2` but on the latest rando version, this causes a StackOverflowException which makes the game crash. Therefore, it's impossible to update the vanilla seed for rando 2.0, unless the ShouldRevert function get modified in a way to allow setting the Ku quest state as a value lower than 4.

**Comment by timoschwarzer** [comment]
This is fixed with 3.0. 3.0 doesn't have any hardcoded states anymore.
