### ISSUE TITLE
Keybind to switch map filter isn't always visible.

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/wotw-rando-client#331]
On normal map filters the keybind to switch filters is shown:
![image](https://user-images.githubusercontent.com/53594055/234017304-621e012c-fcd2-451d-9531-9b117488fbdd.png)
However, on custom filters this bind is not displayed:
![image](https://user-images.githubusercontent.com/53594055/234017439-bdd19d53-582c-41cd-b53b-fc126a961315.png)

**Comment by timoschwarzer** [comment]
I think the shorthand for that is `[MapFilter]`
