### ISSUE TITLE
Hybrid swim aiming mode

### ISSUE THREAD

**Issue by toadettexmushina** [ori-community/wotw-rando-client#337]
Have Ori follow the cursor while swimming if no direction input is given, but otherwise follow directional inputs. I find that although the cursor swimming is far more precise, I often forget to switch to it immediately, since out of water movement is done with key inputs.
Could have a similar option for burrowing too.

**Comment by SiriusAshling** [comment]
To note, Blind Forest has this as its only implementation of Mouse Aiming and it takes some getting used to, but plays well. Then again, Mouse Aim takes some getting used to no matter what and allowing keys to function as well might actually help the transition.
I don't think it would hurt to have all options of keyboardonly/hybrid/mouseonly.

**Comment by timoschwarzer** [comment]
Done
