### ISSUE TITLE
 Multiplayer doesn't recognize current save file anymore

### ISSUE THREAD

**Issue by HopeNya** [ori-community/wotw-rando-client#348]
I am not 100% sure what causes it, but it happened after an hour of playing and reloading the most recent backup save of the game.
![image](https://github.com/ori-community/wotw-rando-client/assets/159170665/cb77397e-ca1d-44c8-a967-e7126663d393)

**Comment by timoschwarzer** [comment]
Closed as I couldn't reproduce anymore. Might have been a missed server update. Please re-open if it happens again, best with reproduction steps.
