### ISSUE TITLE
Having Normal Text Interpolation on the Spoiler Map

### ISSUE THREAD

**Issue by Cleanfel** [ori-community/wotw-rando-client#356]
Suggestion: have the spoiler text color mimic the colors of the pickups so the spoiler map is easier to read than just all yellow (Skills: blue, shards: green, tps: yellow, xp: white, etc.). It can definitely be tricky to try to find stuff on the spoiler map fromt time to time.

**Comment by timoschwarzer** [comment]
Implemented with 12ce1f8a670e1c43a4a2e6a99e2d6ff12e8a0c11
